### ISSUE TITLE
GridFieldDetailForm_ItemRequest::getRecord(); does not exists 3.1.13

### ISSUE THREAD

**Issue by ghost** [dhensby/silverstripe-masquerade#2]
The composer file accepts SS ^3.1.0, but this does not work...

GridFieldDetailForm_ItemRequest::getRecord(); is not present in SS 3.1.13.

changing MasqueradeGridFieldDetailForm_ItemRequest line 11:

$member = $this->getRecord();

to 

$member = $this->record;

makes it work....

**Comment by dhensby** [comment]
closed by f57951c1210606408a37d82998d42d2e48f0e9b2
