### ISSUE TITLE
PHP v7 support?

### ISSUE THREAD

**Issue by adrian-stein** [dhensby/silverstripe-masquerade#4]
Is there any reason why it is not supported in php >v7?

**Comment by dhensby** [comment]
I'm sure it would work once the composer constraints are updated. Want to PR?

**Comment by adrian-stein** [comment]
See https://github.com/dhensby/silverstripe-masquerade/pull/5

**Comment by adrian-stein** [comment]
Fixed with v0.1.2. Thanks
