### ISSUE TITLE
SS4 Upgrade

### ISSUE THREAD

**Issue by muskie9** [dhensby/silverstripe-masquerade#7]
Hi @dhensby, I'm going to be working on upgrading this module to SS4 and just wanted to run the namespacing by you. I was planning on `DHensby\Masquerade` at this point. I didn't see any namespacing in your other source repos.

**Comment by dhensby** [comment]
@muskie9 sorry for the silence on this, yep, that NS looks good :)

**Comment by muskie9** [comment]
No worries, I'll be circling back to this over the next week to hopefully wrap up the final todo's for a PR.

**Comment by dhensby** [comment]
@muskie9 did anything ever come of this 👼 ?

**Comment by muskie9** [comment]
Sorry for the radio silence, we've been on migrations as of late but I'm hoping to get back to this for some of our sites that have a large number of registered users.

**Comment by dhensby** [comment]
OK - thanks for the update

**Comment by lozcalver** [comment]
A client of ours needed it too 😁 PR: https://github.com/dhensby/silverstripe-masquerade/pull/8
